# Generated by Django 4.2.30 on 2026-08-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0010_add_driver_and_lakehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconnection',
            name='connection_type',
            field=models.CharField(choices=[('postgresql', 'PostgreSQL'), ('mysql', 'MySQL'), ('databricks', 'Databricks'), ('db2', 'DB2'), ('oracle', 'Oracle'), ('lakehouse', 'Lakehouse'), ('csv', 'Flat File (CSV)'), ('parquet', 'Flat File (Parquet)'), ('excel', 'Flat File (Excel)'), ('text', 'Flat File (Text)'), ('azure_blob', 'Azure Blob Storage')], max_length=20),
        ),
    ]
