# Generated by Django 4.2.30 on 2026-07-22 05:21

from django.db import migrations, models


def drop_hwm_table(apps, schema_editor):
    vendor = schema_editor.connection.vendor
    with schema_editor.connection.cursor() as cursor:
        if vendor == 'oracle':
            try:
                cursor.execute("DROP INDEX idx_hwm_trigger_date")
            except Exception:
                pass
            try:
                cursor.execute("DROP INDEX idx_hwm_etl_date")
            except Exception:
                pass
            try:
                cursor.execute("DROP INDEX idx_hwm_trigger_name")
            except Exception:
                pass
            try:
                cursor.execute("DROP TABLE hwm_chk")
            except Exception:
                pass
        else:
            cursor.execute("DROP INDEX IF EXISTS idx_hwm_trigger_date")
            cursor.execute("DROP INDEX IF EXISTS idx_hwm_etl_date")
            cursor.execute("DROP INDEX IF EXISTS idx_hwm_trigger_name")
            cursor.execute("DROP TABLE IF EXISTS hwm_chk")


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0007_emailnotification_retry_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='poll_duration_hours',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='trigger_fired_at',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='trigger_last_polled',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='trigger_name',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='trigger_scheduled_time',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='trigger_status',
        ),
        migrations.AlterField(
            model_name='workflow',
            name='schedule_type',
            field=models.CharField(choices=[('manual', 'On Demand'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='manual', max_length=20),
        ),
        migrations.RunPython(drop_hwm_table, reverse_code=migrations.RunPython.noop),
    ]
