# Generated by Django 4.2.30 on 2026-07-07 07:27

from django.db import migrations, models
import django.db.models.deletion


def populate_existing_results(apps, schema_editor):
    ValidationResult = apps.get_model('validations', 'ValidationResult')
    # Loop over all results and populate source/target column names
    for r in ValidationResult.objects.all():
        if r.column_mapping:
            r.source_column = r.column_mapping.source_column
            r.target_column = r.column_mapping.target_column
            r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0014_alter_validationrule_operation'),
        ('validations', '0006_validationrun_workflow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='validationresult',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='validationresult',
            name='source_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='validationresult',
            name='target_column',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='validationresult',
            name='column_mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mappings.columnmapping'),
        ),
        migrations.RunPython(populate_existing_results, reverse_code=migrations.RunPython.noop),
    ]
