# Generated by Django 4.2.30 on 2026-07-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mappings', '0014_alter_validationrule_operation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='mappings.pipelinegroup')),
                ('mapping', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignment', to='mappings.mapping')),
            ],
        ),
    ]
