# Generated by Django 4.2.30 on 2026-07-28 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mappings', '0015_pipelinegroup_pipelinegroupassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapping',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_mappings', to=settings.AUTH_USER_MODEL),
        ),
    ]
